base_url = "gokay-avci.github.io"
title = "Avci Lab"
description = "Computational Materials Science Personal Website"
default_language = "en"
theme = "daisy"
build_search_index = true
generate_feeds = true

taxonomies = [
    { name = "tags", paginate_by = 10, rss = true },
    { name = "categories", paginate_by = 10, rss = true },
]

[markdown]
highlight_code = true
highlight_theme = "base16-ocean-dark"
render_emoji = true

[search]
index_format = "elasticlunr_json"
include_title = true
include_content = true

[extra]
# --- DAISY SETTINGS ---
github = "gokay-avci"
twitter = "---"
email = "gavci@u.lab"

# Theme Toggle Logic
enable_theme_switching = true
theme_toggle = false
daisyui_theme_light = "Emerald"
daisyui_theme_dark = "Forest"

# THEME LIST (Required for Dropdown)
daisyui_themes = [
    "light", "dark", "cupcake", "bumblebee", "emerald", "corporate", 
    "synthwave", "retro", "cyberpunk", "valentine", "halloween", 
    "garden", "forest", "aqua", "lofi", "pastel", "fantasy", 
    "wireframe", "black", "luxury", "dracula", "cmyk", "autumn", 
    "business", "acid", "lemonade", "night", "coffee", "winter"
]

# Navbar (Keys must exist in i18n/en.toml)
[extra.navbar]
links = [
    { url = "about", i18n_key = "nav_about" },
    { url = "projects", i18n_key = "nav_projects" },
    { url = "blog", i18n_key = "nav_journal" },
    { url = "CV", i18n_key = "nav_CV" },
]

[extra.footer]
notice = '• Built with :heart: by @Gokay Avci 2026 •'